# Generated by Django 5.1.5 on 2025-03-05 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=20)),
                ('speaker', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
