# Generated by Django 5.1.5 on 2025-03-05 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_talk_delete_item'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='talk',
            table='talks',
        ),
    ]
