# Generated by Django 5.1.7 on 2025-03-14 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_talk_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('type', models.CharField(choices=[('CASTLE', 'Castle'), ('Competition', 'Competition'), ('Speaker', 'Speaker'), ('Other', 'Other')], default='CASTLE', max_length=12)),
            ],
            options={
                'db_table': 'meetings',
            },
        ),
    ]
