# Generated by Django 5.1.7 on 2025-03-17 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_talk_date_website'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='website',
            table='websites',
        ),
    ]
