# Generated by Django 5.1.7 on 2025-03-17 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_website_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Website',
        ),
    ]
