# Generated by Django 5.1.7 on 2025-03-17 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_delete_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=35)),
                ('type', models.CharField(choices=[('CASTLE', 'Castle'), ('Competition', 'Competition'), ('Speaker', 'Speaker'), ('Other', 'Other')], default='CASTLE', max_length=12)),
            ],
            options={
                'db_table': 'archive',
            },
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('meeting_date', models.DateField()),
            ],
            options={
                'db_table': 'websites',
            },
        ),
    ]
