# Generated by Django 5.1.5 on 2025-03-19 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_archive_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('toggle', models.CharField(choices=[('On', 'On'), ('Off', 'Off')], default='Off', max_length=3)),
            ],
            options={
                'db_table': 'settings',
            },
        ),
        migrations.AddField(
            model_name='talk',
            name='approved',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('No Decision', 'No Decision')], default='No Decision', max_length=12),
        ),
        migrations.AlterField(
            model_name='archive',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
