# Generated by Django 5.1.7 on 2025-04-09 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_setting_talk_approved_alter_archive_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=400)),
                ('img', models.ImageField(blank=True, null=True, upload_to='photos/')),
            ],
            options={
                'db_table': 'events',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('finish_date', models.DateField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=400)),
                ('github', models.URLField(blank=True)),
            ],
            options={
                'db_table': 'projects',
            },
        ),
    ]
