# Generated by Django 5.1.7 on 2025-04-22 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_event_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='email',
            field=models.CharField(default='N/A', max_length=40),
        ),
        migrations.AlterField(
            model_name='talk',
            name='speaker',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='talk',
            name='title',
            field=models.CharField(max_length=40),
        ),
    ]
